services:
  medicationmicroservice.webapi:
    image: medicationmicroservice.webapi
    build:
      context: .
      dockerfile: MedicationMicroservice.WebAPI/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=doctorsdb;Username=postgres;Password=admin
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: doctorsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  medicationmicroservice.cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  prometheus:
    build:
      context: ./MedicationMicroservice.WebAPI
      dockerfile: dockerfile-prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./MedicationMicroservice.WebAPI/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - medicationmicroservice.webapi

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data:
